
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: bokobo2026/app-stateful-flask:91cf06794a1ac66894f56a01f94c0a14fa5b2d40
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DATABASE_URI
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

